### PR TITLE
Skip record from exception

### PR DESCRIPTION
**Pull request by rajdangwal**

### CODE REVIEW

**Review by ypmahajan — APPROVED** [review]
Looks good.

**Comment by ypmahajan** [comment]
@rajdangwal so each time cutting a new version, we need to change the version in build.gradle file?

**Comment by rajdangwal** [comment]
Yes, while doing the release locally we have to update the version there.
The steps are as follows:
1. Commit the code changes
2. Update the version in build.gradle.kts file
3. Commit that as well similar to this PR commit

After the PR is approved
4. Generate a tag with version and push it
5. Run `./gradlew createConfluentArchive`
6. Upload the zip file from ./build/confluent/ to staging bucket

**Comment by aniketshrimal** [comment]
@rajdangwal - Could we add this local release steps to readme if it is already not present there?

**Comment by rajdangwal** [comment]
Sure @aniketshrimal. I will do that. Thanks.

**Pull request merged**
